/* eslint-disable */

declare module 'glob:./sources/{*.ts,**/index.ts}' {
  export const _36kr: typeof import('./sources/_36kr')
  export const baidu: typeof import('./sources/baidu')
  export const bilibili: typeof import('./sources/bilibili')
  export const cankaoxiaoxi: typeof import('./sources/cankaoxiaoxi')
  export const cls: typeof import('./sources/cls/index')
  export const coolapk: typeof import('./sources/coolapk/index')
  export const cto: typeof import('./sources/cto')
  export const douyin: typeof import('./sources/douyin')
  export const dushu: typeof import('./sources/dushu')
  export const fenghuang: typeof import('./sources/fenghuang')
  export const gelonghui: typeof import('./sources/gelonghui')
  export const github: typeof import('./sources/github')
  export const gjyunying: typeof import('./sources/gjyunying')
  export const hackernews: typeof import('./sources/hackernews')
  export const hupu: typeof import('./sources/hupu')
  export const ithome: typeof import('./sources/ithome')
  export const jin10: typeof import('./sources/jin10')
  export const kaopu: typeof import('./sources/kaopu')
  export const kuaishou: typeof import('./sources/kuaishou')
  export const producthunt: typeof import('./sources/producthunt')
  export const sohu: typeof import('./sources/sohu')
  export const solidot: typeof import('./sources/solidot')
  export const sputniknewscn: typeof import('./sources/sputniknewscn')
  export const tengxun: typeof import('./sources/tengxun')
  export const thepaper: typeof import('./sources/thepaper')
  export const tieba: typeof import('./sources/tieba')
  export const toutiao: typeof import('./sources/toutiao')
  export const v2ex: typeof import('./sources/v2ex')
  export const wallstreetcn: typeof import('./sources/wallstreetcn')
  export const wangyi: typeof import('./sources/wangyi')
  export const weibo: typeof import('./sources/weibo')
  export const xiaohongshu: typeof import('./sources/xiaohongshu')
  export const xinlang: typeof import('./sources/xinlang')
  export const xueqiu: typeof import('./sources/xueqiu')
  export const zaobao: typeof import('./sources/zaobao')
  export const zhihu: typeof import('./sources/zhihu')
}
